version: '3.8'

services:
  backend:
    container_name: ssmp-be
    hostname: ssmp-be
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/var/www/html
    env_file:
      - .env                
    networks:
      - app-network

  mysql:
    container_name: ssmp-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    container_name: ssmp-pma
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
